# ===== 基本設置 =====
# 網站名稱，會顯示在瀏覽器標籤和導航列
site_name: 救世者之樹M
# 網站 URL，通常是 GitHub Pages 的位址
site_url: 
# 作者資訊
site_author: Ko-Cheng, Huang
# 網站描述，用於 SEO
site_description: 

# ===== 主題設置 =====
site_url: https://mydomain.org/mysite
theme:
  name: material